config/routes.rb
Rails.application.routes.draw do

  resources :stickies
  resources :comments
  resources :activities, only:[:index]
    
  resources :user_friendships do 
    member do 
      put :accept
    end
  end

  devise_for :users
  

  root 'homepage#index'
  # root 'welcomes#index'

  # IDEAS ROUTES
  get 'ideas/showAll',        to: 'ideas#showAll',          :as => :showAll
  get 'ideas/showAuthorIdea', to: 'ideas#showAuthorIdea',   :as => :showAuthorIdea
  get 'ideas/new',            to: 'ideas#newIdea',          :as => :newIdea
  get 'ideas/showBMC/:id',    to: 'ideas#showBMC',          :as => :showBMC
  get 'ideas/:id',            to: 'ideas#showIdea',         :as => :showIdea
  get 'ideas/editIdea/:id',   to: 'ideas#editIdea',         :as => :editIdea
  post 'ideas/add',           to: 'ideas#add',              :as => :add     
  patch 'ideas/update',       to: 'ideas#update',           :as => :update
  delete 'ideas/:id',         to: 'ideas#delete',           :as => :delete

  # PROFILE ROUTES
  get '/:id',                 to: 'profiles#showProfile',   :as => :showProfile

  # HOMEPAGE ROUTE
  get 'homepage/index',       to: 'homepage#index',         :as => :index

  
  get 'welcome',              to: 'welcomes#index',         :as => :welcomeIndex

  # get "profiles/showProfile", to: 'profiles#showProfile',   :as => :showProfile

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	# before_filter :authenticate_user!

  def index
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="homeWrapper">
	<div class="row">
	
	  <div class="col s12 m12 l4 smallWidth">
	  	<div class="row">
	  		<div class="col s12">

					<%= link_to showAll_path() do%>
						<div class="card-panel showIdeaCard largeCard blue lighten-3">
							<div class="cardBody center">
								<span class="black-text">
					      	<i class="fa fa-globe"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper blue lighten-1">
				      	<span class="foot white-text">All Ideas <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
					<%end%>

	  		</div>
	  	</div>
	  	<div class="row">
	  		<div class="col s6 m6">
					<%= link_to(:controller => "user_friendships", :action => "index" )do %>
						<div class="card-panel showActivityCard smallCard  red lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-heart"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper red lighten-1">
				      	<span class="foot white-text">Friends <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
					<%end%>

	  		</div>
	  		<div class="col s6 m6">
	  			
	  			<%= link_to showAll_path() do%>
						<div class="card-panel createIdeaCard smallCard purple lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-search"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper purple lighten-1">
				      	<span class="foot white-text">Search <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
					<%end%>

	  		</div>
	  	</div>
	  </div>

	  <div class="col s12 m12 l4 smallWidth">
	  	<div class="row">
	  		<div class="col s6 m6">

					<%= link_to activities_path() do%>
						<div class="card-panel showActivityCard smallCard green lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-th-list"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper green lighten-1">
				      	<span class="foot dark-text">Show Activity <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
					<%end%>

	  		</div>
	  		<div class="col s6 m6">

	  			<%= link_to showAll_path() do%>
						<div class="card-panel createIdeaCard smallCard yellow lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-globe"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper yellow lighten-1">
				      	<span class="foot dark-text">Events <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
			    <%end%>

	  		</div>
	  	</div>
	  	<div class="row">
	  		<div class="col s12">

					<%= link_to	newIdea_path() do %>
		  			<div class="card-panel showIdeaCard largeCard red lighten-3">
							<div class="cardBody center">
					      <span class="black-text">				     
					      	<i class="fa fa-rocket"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper red lighten-1">
				      	<span class="foot white-text">Create Idea <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
					<%end%>

	  		</div>
	  	</div>
		</div>

		<div class="col s12 m12 l4 smallWidth">
			<div class="row">
				<div class="col s6 m6">

					<%= link_to showAuthorIdea_path() do%>
						<div class="card-panel createIdeaCard largeCard blue lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-user"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper blue lighten-1">
				      	<span class="foot white-text">My Ideas <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
			    <%end%>

				</div>
				<div class="col s6 m6">

					<%= link_to showAll_path() do%>
						<div class="card-panel createIdeaCard largeCard green lighten-3">
							<div class="cardBody center">
					      <span class="black-text">
					      	<i class="fa fa-info"></i>
					      </span>
				      </div>
				      <div class="cardFooter valign-wrapper green lighten-1">
				      	<span class="foot dark-text">Resources <i class="fa fa-caret-right"></i></span>
				      </div>
				    </div>
			    <%end%>

				</div>
			</div>
			<div class="row">
				<div class="col s12">
				  <% if user_signed_in? %>
						<%= link_to showProfile_path(current_user.profileName) do %>
							<div class="card-panel createIdeaCard smallCard purple lighten-3">
								<div class="cardBody center">
						      <span class="black-text">
						      	<i class="fa fa-cogs"></i>
						      </span>
					      </div>
					      <div class="cardFooter valign-wrapper purple lighten-1">
					      	<span class="foot white-text">Profile <i class="fa fa-caret-right"></i></span>
					      </div>
					    </div>
					  <%end%>
				  <%else%>
						<%= link_to user_registration_path() do %>
					  	<div class="card-panel createIdeaCard smallCard purple lighten-3">
								<div class="cardBody center">
						      <span class="black-text">
						      	<i class="fa fa-cogs"></i>
						      </span>
					      </div>
					      <div class="cardFooter valign-wrapper purple lighten-1">
					      	<span class="foot white-text">Create Account <i class="fa fa-caret-right"></i></span>
					      </div>
					    </div>
				    <%end%>
				  <%end%>
				</div>
			</div>
		</div>

	</div>
</div>