config/routes.rb
Rails.application.routes.draw do

  resources :stickies
  resources :comments
  resources :activities, only:[:index]
    
  resources :user_friendships do 
    member do 
      put :accept
    end
  end

  devise_for :users
  

  root 'homepage#index'
  # root 'welcomes#index'

  # IDEAS ROUTES
  get 'ideas/showAll',        to: 'ideas#showAll',          :as => :showAll
  get 'ideas/showAuthorIdea', to: 'ideas#showAuthorIdea',   :as => :showAuthorIdea
  get 'ideas/new',            to: 'ideas#newIdea',          :as => :newIdea
  get 'ideas/showBMC/:id',    to: 'ideas#showBMC',          :as => :showBMC
  get 'ideas/:id',            to: 'ideas#showIdea',         :as => :showIdea
  get 'ideas/editIdea/:id',   to: 'ideas#editIdea',         :as => :editIdea
  post 'ideas/add',           to: 'ideas#add',              :as => :add     
  patch 'ideas/update',       to: 'ideas#update',           :as => :update
  delete 'ideas/:id',         to: 'ideas#delete',           :as => :delete

  # PROFILE ROUTES
  get '/:id',                 to: 'profiles#showProfile',   :as => :showProfile

  # HOMEPAGE ROUTE
  get 'homepage/index',       to: 'homepage#index',         :as => :index

  
  get 'welcome',              to: 'welcomes#index',         :as => :welcomeIndex

  # get "profiles/showProfile", to: 'profiles#showProfile',   :as => :showProfile

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :authenticate_user!
  def showProfile
  	@user_byName = User.find_by_profileName(params[:id]) 						# RETURNS USER OBJECT: NOTE NOT THE ID
  	@user_comments = Comment.where(:user_id => @user_byName.id)
  	@user_ideas = Idea.where(:author => @user_byName.profileName).page(params[:page]).per(6)
  	@user_friendships = @user_byName.user_friendships.all
  	@friendship = current_user.user_friendships.where(:friend_id => @user_byName.id).pluck(:id) # RETURNS AN ID
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/showProfile.html.erb
<!-- THIS IS WHERE THE PUBLIC PROFILE PAGE FOR A USER WILL BE :) -->
<div class="row">
	<div class="col s12 m10 offset-m1">
		<div class="row">
			<div class="col m6">
				<h3><%=@user_byName.fullName.split.map(&:capitalize).join(' ')%></h3>
				<p class="childElement">@<%=@user_byName.profileName %></p>
				<% if @user_byName != current_user %> 
					<div id = "friend-status">
						<% if current_user.friends.include?(@user_byName)%>
							<%= link_to "Edit Friendship", edit_user_friendship_path(@friendship), class: "btn btn-flat"%> 
						<%else%>
							<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user_byName), id: "add-friendship", class: "btn btn-flat", data: {friend_id: @user_byName.to_param} %> 
						<%end%>
					</div>
				<%else%>
					<%= link_to	edit_user_registration_path(), :class => "btn btn-flat" do %>
		      	Edit Profile
		   		<% end %>
		   		<%= link_to destroy_user_session_path, method: :delete, :class => 'btn btn-flat' do %>
		        Sign Out
		      <% end %>
				<%end%>
			</div>
			<div class="col m6">
				<% if @user_byName.avatar.url.present? %>
		      <%= image_tag(@user_byName.avatar.url(:small), class: "right") %> 
		    <%end%>
			</div>
		</div>

		<!-- DISPLEY THE AUTHORS IDEAS -->
		<div class="row">
			<% if @user_ideas.present?%>
			  <% @user_ideas.each do |ideaItem| %>
				  <div class="col s12 m6 l4">
			 	  	<% if ideaItem.picture.present?%>
			    	<!-- IF THE IDEA HAS A PICTURE -->
			    		<div class="card card-picture small showHide hoverDepth">
				        <div class="card-image waves-effect waves-block waves-light">
				          <%= image_tag(ideaItem.picture_url, :class => "activator") %>
				        </div>
				        <div class="card-content">
				          <span class="card-title grey-text text-darken-4">
					          <h5 class="truncate">
					            <%= link_to showIdea_path(ideaItem.id) do%>
						          	<%= ideaItem.name%>
						          <%end %>
						          <i class="fa fa-angle-up activator right"></i>
						        </h5>
				          </span>
				          <div class="card-author childElement truncate">
				          	<%= ideaItem.author%>
				          </div>
				          <div class="card-img-footer showOnHover">
				          	<%= link_to showIdea_path(ideaItem.id), :class=>"waves-effect waves-red btn-flat right" do%>
				        			<i class="fa fa-trash-o"></i>
				        		<%end%>
				        		<%= link_to showBMC_path(ideaItem.id), :class=>"waves-effect waves-red btn-flat right" do%>
				    					<i class="fa fa-calendar"></i>
				    				<%end%>
					          <%= link_to showIdea_path(ideaItem.id), :class=>"waves-effect waves-red btn-flat right smallBtn" do%>
					        		<i class="fa fa-eye"></i>
					        	<%end%>
				        	</div>
				        </div>
				        <div class="card-reveal">
				          <span class="card-title grey-text text-darken-4 truncate">
				          	<%= ideaItem.name%> <i class="fa fa-angle-down right"></i>
				          </span>
				          <h6 class="truncate"><%=ideaItem.valueProposition%></h6>
			          	<h6 class="truncate"><strong>Customer:</strong> <%=ideaItem.customerSegment%></h6>
			          	<strong>Description:</strong><h6 class=""> <%=ideaItem.description%></h6>
				        </div>
				      </div>
			    	<%else%>
			    		<!-- IF IDEA HAS NO IMAGE -->
			        <div class="card small showHide hoverDepth <%= ideaCardColor(ideaItem.sector) -%>">
			          <div class=" white-black ">
			          	<div class="card-body">
			              <span class="card-title grey-text text-darken-4">	
				              <%= link_to showIdea_path(ideaItem.id) do%>
						        		<h5 class="truncate"><%= ideaItem.name%></h5>
						        	<%end%>
			              </span>
			              <div class="card-author childElement truncate">
				          		<%= ideaItem.author%>
				          	</div>
					          <h6 class="truncate"><%=ideaItem.valueProposition%></h6>
			          		<h6 class="truncate"><strong>Customer:</strong> <%=ideaItem.customerSegment%></h6>
			          		<h6 class="truncate"><strong>Description:</strong> <%=ideaItem.description%></h6>
			        		</div>
			        		<div class="card-footer showOnHover">
			        			<%= link_to delete_path(ideaItem.id), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"waves-effect waves-red btn-flat right smallBtn" do%>
				        			<i class="fa fa-trash-o"></i>
				        		<%end%>
				        		<%= link_to showBMC_path(ideaItem.id), :class=>"waves-effect waves-red btn-flat right" do%>
				    					<i class="fa fa-calendar"></i>
				    				<%end%>
				        		<%= link_to showIdea_path(ideaItem.id), :class=>"waves-effect waves-red btn-flat right smallBtn" do%>
					        		<i class="fa fa-eye"></i>
					        	<%end%>
			          	</div>
			          </div>
			        </div>
			    	<%end%>
			    </div>
			  <%end%>
		  <%else%>
		  	<div class="row">
		      <div class="col s12 m6 l4 noIdeaCard">
		        <div class="card red lighten-3 center">
		          <div class="card-content black-text">
		            <span class="card-title black-text">You have no ideas :(</span>
		            <p>There are currently no ideas. Go add one with the link below!</p>
		          </div>
		          <div class="card-action red lighten-1">
		          	<%= link_to'/ideas/new', :class=>"white-text" do %>
		            	<i class="fa fa-pencil-square-o"></i> Create Idea
		            <% end %>
		          </div>
		        </div>
		      </div>
		    </div>
		  <% end %>
		</div>
		
		<!-- FROM THE kaminari GEM -->
		<div class="row">
		 	<div class="col s12">
				<div class="pagination_links">
			    <%= paginate @user_ideas, :pagination_class => "pagination-medium pagination-centered", :container => false %>
			  </div>
			</div>
		</div>
		<!-- <div class="row">
			<div class="col s12">
			  <div class="page_info center">
			    <%= page_entries_info @user_ideas %>
			  </div>
		 	</div>
		</div> -->

		<div class="row">
			<div class="col s12 m12">
				<!-- <%= link_to 'Friends', user_friendships_path %> -->
				<% @user_friendships.each do |friendship| %>
				  <% friend = friendship.friend %>
				  <!-- <div id="<%= dom_id(friendship) %>" class="friend"> -->
				  <div class="col s3 m2 center showHide">
						<%= image_tag(friend.avatar.url(:thumb))%><br>
			    	<%= friend.profileName %>
				    <% if @user_byName == current_user %>
					    <div class="">
				        <% if friendship.pending? %>
				          <em>Pending</em>
				          <div class="showOnHover">
					          <hr>
					          <%= link_to "Delete request", edit_user_friendship_path(friendship)%>
				          </div>
				        <% end %>
				        <% if friendship.requested? %>
				          <em>Requested</em>
				          <div class="showOnHover">
					          <hr>
				          	<%= link_to "Accept friendship", edit_user_friendship_path(friendship)%>.
				          </div>
				        <% end %>
				        <% if friendship.accepted? %>
				          <em>Friend</em>
				          <div class="showOnHover">
					          <hr>
				          	<%= link_to "Update friendship", edit_user_friendship_path(friendship)%>
				          </div>
				        <% end %>
					    </div>
						<% end %>
					<!-- </div> -->
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>