config/routes.rb
Rails.application.routes.draw do

  resources :stickies
  resources :comments
  resources :activities, only:[:index]
    
  resources :user_friendships do 
    member do 
      put :accept
    end
  end

  devise_for :users
  

  root 'homepage#index'
  # root 'welcomes#index'

  # IDEAS ROUTES
  get 'ideas/showAll',        to: 'ideas#showAll',          :as => :showAll
  get 'ideas/showAuthorIdea', to: 'ideas#showAuthorIdea',   :as => :showAuthorIdea
  get 'ideas/new',            to: 'ideas#newIdea',          :as => :newIdea
  get 'ideas/showBMC/:id',    to: 'ideas#showBMC',          :as => :showBMC
  get 'ideas/:id',            to: 'ideas#showIdea',         :as => :showIdea
  get 'ideas/editIdea/:id',   to: 'ideas#editIdea',         :as => :editIdea
  post 'ideas/add',           to: 'ideas#add',              :as => :add     
  patch 'ideas/update',       to: 'ideas#update',           :as => :update
  delete 'ideas/:id',         to: 'ideas#delete',           :as => :delete

  # PROFILE ROUTES
  get '/:id',                 to: 'profiles#showProfile',   :as => :showProfile

  # HOMEPAGE ROUTE
  get 'homepage/index',       to: 'homepage#index',         :as => :index

  
  get 'welcome',              to: 'welcomes#index',         :as => :welcomeIndex

  # get "profiles/showProfile", to: 'profiles#showProfile',   :as => :showProfile

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :idea
	belongs_to :user

	belongs_to :parent, :class_name => "Comment", :foreign_key => "parent_comment_id"
	has_many :child_comments, :class_name => "Comment", :foreign_key => "parent_comment_id"

	validates :body, :user_id, :idea_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        current_user.createActivity(@comment, "created")
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        current_user.createActivity(@comment, "updated")
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    current_user.createActivity(@comment, "deleted")
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      # THIS IS WRONG: GETTING POST ID
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :idea_id, :user_id, :parent_comment_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h5>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'New Comment' %><br>
    <%= f.text_area :body, :class => "commentBodyEnter materialize-textarea", :length =>"120"%>
  </div>

	<%= f.hidden_field :user_id, :value => current_user.id %>

  <% if params[:data] %>
    <% @pcid = params[:data]["parent_comment_id"] %>
    <%= f.hidden_field :idea_id, :value => params[:data]["idea_id"] %>
  <% else %>
    <%= f.hidden_field :idea_id %>
  <% end %>

  <%= f.hidden_field :parent_comment_id, :value => @pcid %>
  <div class="actions">
    <%= f.submit "Add Comment", class: "btn red addCommentBtn"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
	<%= render 'form' %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Idea</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.idea_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <% if current_user.id == comment.user_id %> 
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Comment', new_comment_path %> -->

app/views/comments/new.html.erb
<h1>New Comment</h1>
	<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="showHide">
		<!-- SHOW AUTHOR THUMBNAIL IMAGE -->

		<!-- NEW -->
		<% level ||= 0 %>
		<% comment ||= @comment %>
		<% idea ||= comment.idea %>

		<% level.times do  %>
			<%= '>' %>
		<% end %>
		<%= image_tag(comment.user.avatar.url(:thumb).to_s, :class=>"left")%>
		<strong><%= comment.user.profileName %> says:</strong>

		<!-- NEW -->
		<%= comment.body %>
		<%= link_to new_comment_path(:data => {:parent_comment_id => comment.id, :idea_id => idea.id}), :class =>"commentForm showOnHover" do%>
			<i class="fa fa-reply"></i></i>
		<%end%>

		<% if current_user.id == comment.user_id %>

			<%= link_to edit_comment_path(comment), :class =>"commentForm showOnHover" do%>
				<i class="fa fa-pencil-square-o"></i>
			<%end%>
			<%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"commentForm showOnHover" do%>
				<i class="fa fa-times"></i>
			<% end %>
		<% end %>

		<% comment.child_comments.each do |child| %>
			<br />
			<%= render file: 'comments/show', locals: {comment: child, idea: @idea, level: (level + 1)} %>
		<% end %>

</div>