config/routes.rb
Rails.application.routes.draw do

  resources :stickies
  resources :comments
  resources :activities, only:[:index]
    
  resources :user_friendships do 
    member do 
      put :accept
    end
  end

  devise_for :users
  

  root 'homepage#index'
  # root 'welcomes#index'

  # IDEAS ROUTES
  get 'ideas/showAll',        to: 'ideas#showAll',          :as => :showAll
  get 'ideas/showAuthorIdea', to: 'ideas#showAuthorIdea',   :as => :showAuthorIdea
  get 'ideas/new',            to: 'ideas#newIdea',          :as => :newIdea
  get 'ideas/showBMC/:id',    to: 'ideas#showBMC',          :as => :showBMC
  get 'ideas/:id',            to: 'ideas#showIdea',         :as => :showIdea
  get 'ideas/editIdea/:id',   to: 'ideas#editIdea',         :as => :editIdea
  post 'ideas/add',           to: 'ideas#add',              :as => :add     
  patch 'ideas/update',       to: 'ideas#update',           :as => :update
  delete 'ideas/:id',         to: 'ideas#delete',           :as => :delete

  # PROFILE ROUTES
  get '/:id',                 to: 'profiles#showProfile',   :as => :showProfile

  # HOMEPAGE ROUTE
  get 'homepage/index',       to: 'homepage#index',         :as => :index

  
  get 'welcome',              to: 'welcomes#index',         :as => :welcomeIndex

  # get "profiles/showProfile", to: 'profiles#showProfile',   :as => :showProfile

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/sticky.rb
class Sticky < ActiveRecord::Base
	SECTIONS = [
    ['Key Partners','Key Partners'],
    ['Key Activities','Key Activities'],
    ['Key Resources','Key Resources'],
    ['Value Proposition','Value Proposition'],
    ['Customer Relationships','Customer Relationships'],
    ['Channels','Channels'],
    ['Customer Segments','Customer Segments'],
    ['Cost Structure','Cost Structure'],
    ['Revenue Streams','Revenue Streams']
  ]
  VALIDATESECTION = ["Key Partners", "Key Activities", "Key Resources", "Value Proposition", "Customer Relationships", "Channels", "Customer Segments", "Cost Structure", "Revenue Streams"]
	belongs_to :idea
	belongs_to :user
	validates :body, :user_id, :idea_id, :section, presence: true

	# Makes sure the only thing included is one of the strings above
	validates :section, inclusion: VALIDATESECTION
end

app/controllers/stickies_controller.rb
class StickiesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_sticky, only: [:show, :edit, :update, :destroy]

  # GET /stickies
  # GET /stickies.json
  def index
    @stickies = Sticky.all
  end

  # GET /stickies/1
  # GET /stickies/1.json
  def show
  end

  # GET /stickies/new
  def new
    @sticky = Sticky.new
  end

  # GET /stickies/1/edit
  def edit
  end

  # POST /stickies
  # POST /stickies.json
  def create
    @sticky = Sticky.new(sticky_params)
    @stickySection = ["Key Partners", "Key Activities","Key Resources","Value Proposition","Customer Relationships","Chanels","Customer Segments", "Cost Structure","Revenue Streams"]
    respond_to do |format|
      if @sticky.save
        current_user.createActivity(@sticky, "created")
        format.html { redirect_to @sticky, notice: 'Sticky was successfully created.' }
        format.json { render :show, status: :created, location: @sticky }
      else
        format.html { render :new }
        format.json { render json: @sticky.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stickies/1
  # PATCH/PUT /stickies/1.json
  def update
    respond_to do |format|
      if @sticky.update(sticky_params)
        current_user.createActivity(@sticky, "updated")
        format.html { redirect_to @sticky, notice: 'Sticky was successfully updated.' }
        format.json { render :show, status: :ok, location: @sticky }
      else
        format.html { render :edit }
        format.json { render json: @sticky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickies/1
  # DELETE /stickies/1.json
  def destroy
    @sticky.destroy
    current_user.createActivity(@sticky, "deleted")

    respond_to do |format|
      format.html { redirect_to stickies_url, notice: 'Sticky was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticky
      @sticky = Sticky.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticky_params
      params.require(:sticky).permit(:body, :user_id, :idea_id, :section, :stage)
    end
end

app/helpers/stickies_helper.rb
module StickiesHelper
end

app/views/stickies/_form.html.erb
<%= form_for(@sticky) do |f| %>

  <% if @sticky.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(@sticky.errors.count, "error") %> prohibited this sticky from being saved:</h5>
      <ul>
        <% @sticky.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- <%= f.label :'New Hypothesis' %><br> -->
    <%= f.text_area :body, :class => "commentBodyEnter materialize-textarea", :length =>"120"%>
  </div>
  <div class="input-field  field col s12">
    <%= f.select :section, Sticky::SECTIONS, {}, {class: 'browser-default'}%>
  </div>
  <%= f.hidden_field :idea_id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit "Add Hypothesis", class: "modal-action modal-close btn-flat addHypothesis right"%>
  </div>
<% end %>

app/views/stickies/edit.html.erb
<h1>Editing Sticky</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticky %> |
<%= link_to 'Back', stickies_path %>

app/views/stickies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stickies</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Idea ID</th>
      <th>Author</th>
      <th>Section</th>
      <th>Stage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stickies.each do |sticky| %>
      <tr>
        <td><%= sticky.body %></td>
        <td><%= sticky.idea_id %></td>
        <td><%= sticky.user_id %></td>
        <td><%= sticky.section %></td>
        <td><%= sticky.stage %></td>
        <td><%= link_to 'Show', sticky %></td>
        <td><%= link_to 'Edit', edit_sticky_path(sticky) %></td>
        <td><%= link_to 'Destroy', sticky, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sticky', new_sticky_path %>

app/views/stickies/new.html.erb
<h1>New Sticky</h1>

<%= render 'form' %>

<%= link_to 'Back', stickies_path %>

app/views/stickies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @sticky.body %>
</p>

<p>
  <strong>Idea_ID:</strong>
  <%= @sticky.idea_id %>
</p>

<p>
  <strong>Author:</strong>
  <%= @sticky.user_id %>
</p>

<p>
  <strong>Section:</strong>
  <%= @sticky.section %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @sticky.stage %>
</p>

<%= link_to 'Edit', edit_sticky_path(@sticky) %> |
<%= link_to 'Back', stickies_path %>